services:
    postgres:
        image: postgres:16-alpine
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER:-pipeline} -d ${POSTGRES_DB:-stock_pipeline}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
        ports:
            - '5050:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres

    neo4j:
        image: neo4j:5
        container_name: neo4j
        ports:
            - '7474:7474' # Browser UI
            - '7687:7687' # Bolt protocol (app connection)
        environment:
            NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
            NEO4J_PLUGINS: '["apoc", "apoc-extended"]'
            NEO4J_dbms_security_procedures_unrestricted: 'apoc.*'
            NEO4J_apoc_import_file_enabled: 'true'
            NEO4J_apoc_initializer_neo4j_0: 'CALL apoc.cypher.runFile("file:///init.cypher")'
        volumes:
            - neo4j_data:/data
            - neo4j_logs:/logs
            - ./infra/neo4j/init.cypher:/var/lib/neo4j/import/init.cypher
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'wget --quiet --tries=1 --spider http://localhost:7474 || exit 1',
                ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s

        restart: unless-stopped

    redis:
        image: redis:7
        restart: always
        ports:
            - '6379:6379'
        command: >
            redis-server
            --requirepass ${REDIS_PASSWORD}
            --appendonly yes
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5

    restapi:
        build:
            context: .
            dockerfile: services/RestApi/Dockerfile
        image: stockguardian-restapi:latest
        restart: unless-stopped
        ports:
            - '8080:8080'
        environment:
            POSTGRES_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-stock_pipeline}
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
        depends_on:
            - postgres

    tickerAnalyzer:
        build:
            context: .
            dockerfile: services/TickerAnalyzer/Dockerfile
        image: stockguardian-ticker-analyzer:latest
        restart: unless-stopped
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_STREAM_KEY: ${TICKER_ANALYZER_SERVICE_REDIS_STREAM_KEY}
            REDIS_GROUP_NAME: ${TICKER_ANALYZER_SERVICE_REDIS_GROUP_NAME}
            REDIS_CONSUMER_NAME: analyzer-service-1
            REDIS_BLOCK_TIMEOUT_MS: 2000
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            NEO4J_URI: bolt://neo4j:7687
            NEO4J_USER: ${NEO4J_USER}
            NEO4J_PASSWORD: ${NEO4J_PASSWORD}
            LLM_API_KEY: ${GEMINI_API_KEY}
        depends_on:
            - redis
            - neo4j

volumes:
    postgres_data:
    pgadmin_data:
    neo4j_data:
    neo4j_logs:
    redis_data:
