import json
import logging
from typing import Any, Dict

from redis import Redis, ConnectionError

logger = logging.getLogger(__name__)


class RedisStreamPublisher:
	def __init__(self, redis_client: Redis):
		self.redis = redis_client
	
	def publish(self, data: Dict[str, Any], stream_name: str) -> bytes:
		"""
		Publishes a message to the Redis stream.
		
		:param stream_name: The key of the Redis stream to which the message will be published.
		:param data: The dictionary containing the payload data to be serialized into JSON.
		:return: The unique byte string ID generated by Redis for the published message.
		"""
		
		try:
			payload = {'data': json.dumps(data)}
			
			message_id = self.redis.xadd(name=stream_name, fields=payload)
			
			logger.info(f"Successfully published message {message_id} to stream '{stream_name}'")
			return message_id
		
		except ConnectionError as e:
			logger.error(f"Redis connection error while publishing to '{stream_name}': {e}")
			raise e
		except Exception as e:
			logger.error(f"Failed to publish message to stream '{stream_name}': {e}", exc_info=True)
			raise e
